name: Publish Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'docs/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish Wiki
        uses: theos/github-wiki-publish-action@v1
        with:
          path: "docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          GH_WIKI_REPOSITORY: theos/theos
